//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import xiid24.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class fdfdf extends Project {
    private JLabel jcomp1;
    private JLabel jcomp2;
    private JComboBox jcbExp;
    private JLabel jcomp4;
    private JLabel jcomp5;
    private JLabel jcomp6;
    private JComboBox jcomp7;
    private JLabel jcomp8;
    private JComboBox jcomp9;
    private JLabel jcomp10;
    private JTextArea jcomp11;
    private JButton jcomp12;

    public fdfdf() {
        //construct preComponents
        String[] jcbExpItems = {"Select", "Fresher", "Less than 5 yrs", "5 - 10 yrs", "10 - 20 yrs", "Above 25 yrs"};
        String[] jcomp7Items = {"< 3 Lakhs ", "3 - 7 lakhs", "7 - 15 lakhs", "> 15 lakhs"};
        String[] jcomp9Items = {"Select", "Accounts / Finance / Tax/ CSI", "Architecture", "Restaurant / Hotels", "Web / Graphic Design", "Journalism", "Banking", "Insurance", "Pharma / Medical", "Engineering", "elf Employed"};

        //construct components
        jcomp1 = new JLabel ("Total Experience:");
        jcomp2 = new JLabel ("");
        jcbExp = new JComboBox (jcbExpItems);
        jcomp4 = new JLabel ("Resume  -   Page 2");
        jcomp5 = new JLabel ("Current Annual Salary:");
        jcomp6 = new JLabel ("(In Rupees)");
        jcomp7 = new JComboBox (jcomp7Items);
        jcomp8 = new JLabel ("Functional Area:");
        jcomp9 = new JComboBox (jcomp9Items);
        jcomp10 = new JLabel ("Key Skills:");
        jcomp11 = new JTextArea (5, 5);
        jcomp12 = new JButton ("Send Resume");

        //adjust size and set layout
        setPreferredSize (new Dimension (735, 611));
        setLayout (null);

        //add components
        add (jcomp1);
        add (jcomp2);
        add (jcbExp);
        add (jcomp4);
        add (jcomp5);
        add (jcomp6);
        add (jcomp7);
        add (jcomp8);
        add (jcomp9);
        add (jcomp10);
        add (jcomp11);
        add (jcomp12);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (45, 50, 100, 25);
        jcomp2.setBounds (275, 0, 100, 25);
        jcbExp.setBounds (155, 50, 100, 25);
        jcomp4.setBounds (250, 10, 110, 25);
        jcomp5.setBounds (40, 90, 130, 25);
        jcomp6.setBounds (40, 115, 70, 20);
        jcomp7.setBounds (175, 90, 120, 25);
        jcomp8.setBounds (40, 155, 100, 25);
        jcomp9.setBounds (155, 155, 220, 25);
        jcomp10.setBounds (40, 195, 70, 25);
        jcomp11.setBounds (140, 195, 290, 65);
        jcomp12.setBounds (205, 295, 115, 25);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("fdfdf");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new fdfdf());
        frame.pack();
        frame.setVisible (true);
    }
}
